---
- hosts: all

  tasks:

    - name: install the EPEL release rpm 
      become: yes
      become_user: root
      yum:
        name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Install httpd
      become: yes
      become_user: root
      yum:
        name: httpd
        state: latest

    - name : Copy index file
      become: yes
      become_user: root
      copy:
        remote_src: yes
        src: "/tmp/devops/index.html"
        dest: "/var/www/html/index.html"
        owner: apache
        group: apache
        mode: 0755

    - name: Start Apache
      become: yes
      become_user: root
      service: 
        name: httpd 
        state: started
        enabled: yes  